[package]
name = "leetcode_challenges"
version = "0.1.0"
authors = ["Carson Rajcan <carajcan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
doctest = false
pretty_assertions = "1.2.1"